### ISSUE TITLE
OSDCloud drops during stage of downloading drivers from MS Update Catalog while in WinPE

### ISSUE THREAD

**Issue by gwblok** [OSDeploy/OSD#122]
**Describe the bug**
When running OSDCloud, it MIGHT Fail to download drivers from Windows Update Catalog in WinPE

**To Reproduce**
Run OSDCloud and MAYBE it will happen.  I've had mixed results on different hardware.
Test machine that consistently failed: HP ProDesk 400 G1 - 18E9

**Expected behavior**
It would download successfully

**Screenshots**
![image](https://github.com/OSDeploy/OSD/assets/26312309/32c13395-91e0-42d8-be23-9c5b61bba0f1)

**Additional context**
https://twitter.com/gwblok/status/1766243562033922132

**Comment by gwblok** [comment]
I'm working on a Fix, just uploaded a Try/Catch to hopefully allow it to continue when this happens.
@OSDeploy, I'd love for you to get your eyes on this sometime.  @akosbakos also witnessed this (it's his screen capture)

**Comment by gwblok** [comment]
The error message happens right after Line 88 in the Save-MSUpCatDriver.ps1 file.  I've added the Try / Catch for now.
Unsure what the real fix would be.

**Comment by 0x4448** [comment]
Pretty sure the error is here:

https://github.com/OSDeploy/OSD/blob/b1666edd896bd46cba1a6fea3db2052a1b5dd0f7/Public/Functions/MicrosoftCatalog/Save-MsUpCatDriver.ps1#L109

When all the if-statements between lines 93-107 fail to find anything, the variable is null. Changing the condition in line 109 to one of these might fix it:

```powershell
$null -ne $WindowsUpdateDriver

$null -ne $WindowsUpdateDriver -and $WindowsUpdateDriver.Guid
```

**Comment by AkosBakos** [comment]
I am not even able to create/change the ISO file:
![image](https://github.com/OSDeploy/OSD/assets/44706641/1837e46a-675f-4b74-a989-b4c8e6cfd152)

**Comment by AkosBakos** [comment]
@0x4448 check the newest release, 24.3.10.1.
It should work now

**Comment by gwblok** [comment]
David did some updates for 24.3.10.1 - Issue should be resolved now.  I'll do some testing, but I'm closing for now.

**Comment by AkosBakos** [comment]
#=======================================================================
Write-SectionHeader "[PreOS] Prepare Firmware Tasks"
#=======================================================================
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
[System.Net.WebRequest]::DefaultWebProxy.Credentials = [System.Net.CredentialCache]::DefaultCredentials
Register-PSRepository -Default -Verbose
Set-PSRepository -Name PSGallery -InstallationPolicy Trusted -Verbose
Install-Module -Name MSCatalog -Force -Verbose -SkipPublisherCheck -AllowClobber -Repository PSGallery

**Comment by gwblok** [comment]
@AkosBakos, where would that go?

Looks like there are a couple of scripts in OSD module that install that module, so we'd have to make sure we got all of them.

I wonder if we should have a separate function for installing that module, then use that function in all of the different places it's called.

**Comment by AkosBakos** [comment]
Still the same issue in the WinPE phase: ![image](https://github.com/OSDeploy/OSD/assets/44706641/7bf6f9c0-1170-4edc-b8b9-13ab6a5c631e)

When I invoke the Start-OSDCloud for the second time, it goes throw. 😳

**Comment by gwblok** [comment]
Considering Closed for now with recently update to OSD Module, please create a new issue if the problem comes up again.
